/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'awilkinson' at '01/09/15 21:27' with Gradle 2.4
 *
 * @author awilkinson, @date 01/09/15 21:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
